# Generated by Django 4.1.5 on 2023-01-21 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=10, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('faculty', models.CharField(blank=True, choices=[('COUNSELLOR', 'COUNSELLOR'), ('RESEARCH ASSISTANT', 'RESEARCH ASSISTANT'), ('GRAPHIC DESIGNER', 'GRAPHIC DESIGNER'), ('WEBDEVELOPER', 'WEBDEVELOPER'), ('TEACHER', 'TEACHER'), ('ACCOUNTANT', 'ACCOUNTANT'), ('VIDEO EDITOR', 'VIDEO EDITOR'), ('MARKETING', 'MARKETING')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=15)),
                ('Education', models.CharField(choices=[('sslc', 'sslc'), ('plustwo', 'plustwo'), ('degree', 'degree'), ('pg', 'pg'), ('BEd', 'BEd'), ('phd', 'phd')], max_length=50)),
                ('experience', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('IT', 'IT'), ('HISTORY', 'HISTORY'), ('CURRENT AFFAIRS', 'CURRENT AFFAIRS')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('useuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('psc', 'psc'), ('ssc', 'ssc'), ('bank', 'bank'), ('ugc', 'ugc'), ('net', 'net')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
