# Generated by Django 4.1.5 on 2023-01-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_subject_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quarter_1', models.ManyToManyField(related_name='quarter_1_quarter', to='manager.quarter')),
                ('quarter_2', models.ManyToManyField(related_name='quarter_2_quarter', to='manager.quarter')),
                ('quarter_3', models.ManyToManyField(related_name='quarter_3_quarter', to='manager.quarter')),
                ('quarter_4', models.ManyToManyField(related_name='quarter_4_quarter', to='manager.quarter')),
            ],
        ),
    ]
