# Generated by Django 4.1.5 on 2023-01-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subject_alter_teacher_subject'),
        ('manager', '0003_alter_timetable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_4',
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1_subject', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2_subject', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_3_subject', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_4_subject', to='accounts.subject'),
        ),
    ]
